Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  def create_shared_folder(machine, host_path, guest_path)
    machine.vm.synced_folder host_path, guest_path
  end

  def simple_provision(machine)
    machine.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get upgrade -y
    SHELL
  end

  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "publicweb"
    vm1.vm.network "private_network", type: "dhcp"
    create_shared_folder(vm1, "./shared/vm1", "/home/vagrant/shared")
    simple_provision(vm1)
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "privateweb"
    vm2.vm.network "private_network", ip: "192.168.56.10"
    create_shared_folder(vm2, "./shared/vm2", "/home/vagrant/shared")
    vm2.vm.provision "shell", path: "provision_vm2.sh"
  end

  config.vm.define "vm3" do |vm3|
    vm3.vm.hostname = "publicstaticip"
    vm3.vm.network "private_network", type: "static", ip: "192.168.1.100"
    create_shared_folder(vm3, "./shared/vm3", "/home/vagrant/shared")
    simple_provision(vm3)
  end

  (1..3).each do |i|
    config.vm.define "additional_vm#{i}" do |vm|
      vm.vm.hostname = "additional_vm#{i}"
      vm.vm.network "public_network", type: "dhcp"
      create_shared_folder(vm, "./shared/additional_vm#{i}", "/home/vagrant/shared")
      simple_provision(vm)
    end
  end
end